#!/usr/bin/env bash
# Installs nginx and configures it to listen on port 80
# Prints "Hello World" to the default Nginx index page

# Update package lists
sudo apt-get -y update

# Install nginx
sudo apt-get -y install nginx

# Set permissions to allow writing to the index file
sudo chmod o+w /var/www/html/index.nginx-debian.html

# Replace the default index file with "Hello World!"
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# Restart nginx to apply changes
sudo service nginx restart
