#!/usr/bin/env bash
# Install nginx on your web-01 server

# Update package lists
apt-get -y update

# Install nginx
apt-get -y install nginx

# Create index file
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Configure redirection for /redirect_me
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Configure 404 error page
sed -i "/listen 80 default_server/a error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
